# Generated by Django 4.2.5 on 2023-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.CharField(default='guest', max_length=100),
            preserve_default=False,
        ),
    ]
